### PR TITLE
release changes and fixes

### PR DESCRIPTION
**Pull request by aarlaud**
- [x] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- [x] Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
- [x] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)

### What this does

Release changes and fixes in snyk-delta
Adds passIfNoBaseline option to not fail in case there is not baseline/monitored project snapshot to compare against and the current test contains vulns. It typically helps on the first iterations when we try to get the Snyk mechanic in and get a monitored snapshot.

### CODE REVIEW

**Comment by jeetchoudhary** [comment]
@mathild3r  we don't run snyk-delta explicitly, I believe snyk_prevent_commit-status invokes it internally. will passing --setPassIfNoBaseline to snyk_prevent_commit-status  work?

**Comment by mathild3r** [comment]
@jeetchoudhary it won't, setPassIfNoBaseline is a snyk-delta option, and it's set to false. so if you use snyk-prevent-commit-status on its own the default behaviour will apply. it will fail if there is no baseline.

**Comment by jeetchoudhary** [comment]
ohh. that's a bummer then.  Users using snyk-prevent-commit-status alone are left with no option then.  Is there is a way you can support it?

**Comment by jeetchoudhary** [comment]
we had a discussion with Andre and he is aware of the fact that Salesforce uses snyk-prevent-commit-status alone

**Comment by aarlaud** [comment]
we're fixing that. looking to push out a version shortly.

**Comment by aarlaud** [comment]
Check out the v2.0.6 @jeetchoudhary , should do the trick.

**Comment by gec-svc-dva-strata** [comment]
thank @aarlaud let me check this one out.

**Pull request merged**
